/**
 * The people of Sanctum-9.
 *
 * Named NPCs are not set dressing — each one stands next to a mechanic and
 * explains it in character. The rule for their dialogue: every claim an NPC
 * makes about the Fabric must be literally true of this build. A city that lies
 * to you about its own security model would be a strange thing to demo.
 */
import type { DistrictId } from "./districts";

export type NpcKind = "informant" | "phisher" | "herald" | "ripperdoc" | "quartermaster";

export interface Npc {
  id: string;
  name: string;
  tag: string;
  kind: NpcKind;
  /** World-space [x, z]. */
  pos: [number, number];
  district: DistrictId;
  color: number;
  /** Cycled on each interaction. */
  lines: string[];
  /** Optional bounty this NPC hands out (a counter-based objective). */
  bounty?: { id: string; title: string; hint: string; event: string; count: number; reward: number };
  /** Non-tidified drone: its data socket at /api/legacy/npc/<hackable> leaks. */
  hackable?: string;
}

export const NPCS: Npc[] = [
  {
    id: "mox",
    name: "MOX",
    tag: "street fixer",
    kind: "informant",
    pos: [-26, 88],
    district: "sprawl",
    color: 0x00e5ff,
    lines: [
      "New jack. Out here in the Sprawl the old gates still run — forgeable passes, default logins, keys leaking out of config files. Everybody robs everybody. It's just the weather. You get used to it, or you get to the Core.",
      "That golden district to the north? The one with the light show that never goes dark? That's the only place the Fabric fully reached. Your name there is signed by twenty nodes that each know a piece of you. Nobody can be you. Nobody. People spend their whole lives trying to get a clearance in.",
      "Kid down the block patched his client so our barriers looked green and walked through into an empty lot. Out here that works. They say try it on the Vault Core gate and it just… glitches. Laughs at you. Because there's nothing to forge.",
    ],
  },
  {
    id: "sable",
    name: "SABLE",
    tag: "corpo netrunner",
    kind: "phisher",
    pos: [22, -150],
    district: "sprawl",
    color: 0xff2b46,
    lines: [
      "Hey. Hey. You want into the substation? Just hand me your jack for a second. I'll clone it, you'll be inside in thirty. Out here that still works — the Sprawl never got the Fabric.",
      "Come on. It's just a token. What's the worst that happens?",
      "…you're not biting. Smart. Honestly? I do this because I have to. If they ever tidify this quarter I'm out of a job — and I'd celebrate. Imagine a city where I couldn't steal you even if you begged me. They say that's the Core. Must be nice.",
    ],
  },
  {
    id: "wren",
    name: "WREN",
    tag: "shard quartermaster",
    kind: "quartermaster",
    pos: [-88, -34],
    district: "sprawl",
    color: 0x39ff88,
    lines: [
      "Everything you pull out there gets sealed to you before it hits any disk. Fresh key every single time — no reuse, not even between two shards you grab in the same minute.",
      "People ask me to unlock their stash when they lose their password. I can't. Not 'policy' can't. The key was never in one piece anywhere, so there's nothing for me to fetch.",
      "The corps raid this district's servers about twice a year. They always get in — we're the old stack out here. They always leave with base64 and a headache. That's the closest the Sprawl gets to safe.",
      "Word is the whole Vault Core works the way one shard of mine does: nothing readable ever sits in one place. A district where a raid comes up empty every single time. I keep one shard like a prayer for it.",
    ],
  },
  {
    id: "okada",
    name: "DR. OKADA",
    tag: "ripperdoc",
    kind: "ripperdoc",
    pos: [-196, -26],
    district: "sprawl",
    color: 0xff3355,
    lines: [
      "My clinic out here still leaks — a reception drone kept plaintext copies it never should have, and any runner with a rainbow table cracks my maintenance login. I patch bodies all day and can't patch my own front door.",
      "I keep records I cannot read. Sealed the moment they're written. When the auditors come I hand them the whole cabinet and they leave unhappy. It's the one Fabric-blessed thing I own, and I cling to it.",
      "They say inside the Core every clinic works like my record cabinet — top to bottom, no leak, no crack, no drone hoarding a plaintext copy. A ripperdoc could retire happy in a place like that. Maybe one day the council signs me a ghost clearance and I find out.",
    ],
  },
  {
    id: "kestrel",
    name: "KESTREL",
    tag: "council herald",
    kind: "herald",
    pos: [64, 44],
    district: "sprawl",
    color: 0xb46cff,
    lines: [
      "Ghost clearance isn't bought. A council member puts your name up, and it sits there — a real request, going nowhere — until enough of them sign it in their own enclaves.",
      "One of them alone can't do it. Neither can the machine this city runs on. That's the arrangement, and it's held so far.",
      "Ghost clearance is the only key that opens the golden gate — and it can't be stolen, only granted, by a quorum signing in their own enclaves. That's why every soul in the Sprawl dreams of it. You can't hack your way into the Core. You can only be raised into it.",
      "Watch the commit fail while it's short. Four-twelve. The Fabric won't seal what the quorum hasn't signed. Somewhere behind the golden wall, your name is waiting for enough of them to say yes.",
    ],
  },
  {
    id: "hollis",
    name: "HOLLIS",
    tag: "crew quartermaster",
    kind: "informant",
    pos: [330, 26],
    district: "spire",
    color: 0xffc247,
    lines: [
      "Kaishin Spire looks tidified but it isn't — not really. The concierge session rides the wire in the clear, no binding. Anyone who sniffs it wears my face. Up here the marble's nicer, but the locks are just as fake.",
      "I keep the crew vault, and it's the one honest thing in my life: a drop belongs to whoever satisfies the contract, checked inside every node. It's a taste of what the Core is, top to bottom. I dream of living in a whole district like that.",
      "The couriers who run cargo to the golden gate come back quiet. They say inside there's no such thing as a stolen token — the Fabric binds every one to the hand that made it. A replay just… dies. I'd trade the Spire for a broom closet in there.",
    ],
  },
  {
    id: "ash",
    name: "ASH",
    tag: "substation ghost",
    kind: "informant",
    pos: [-30, -330],
    district: "blackwall",
    color: 0x39ff88,
    lines: [
      "Substation's still the old stack. Any kid with an unsigned token walks through my front door — I've been forged into four times this month. I patch it, they patch around it. I'm so tired.",
      "You know what I dream about? Waking up one morning and the Fabric's reached us. No password to steal, no pass to forge. Just… nobody can be me but me. They say that's what it's like inside the Core.",
      "They say the Vault Core has no doors at all. Doesn't need them. You walk the golden streets and nothing there can be taken from you — not by a corp, not by an admin, not by the machine itself. I want to see it before I die down here.",
    ],
  },
  {
    id: "architect",
    name: "THE ARCHITECT",
    tag: "she built the fabric",
    kind: "herald",
    pos: [0, 168],
    district: "sprawl",
    color: 0x6cf5ff,
    lines: [
      "You keep looking for the vault door. There isn't one. I didn't build a stronger lock — I removed the thing a lock protects.",
      "Ownership used to be a promise someone made you. Here it's a fact of the mathematics. Your account is yours because no one — not me, not the operator, not the machine — was ever given the keys to take it.",
      "Security, privacy, governance, sovereignty — people sell those as five products. They're one move: take authority away from everyone. The rest falls out.",
      "The old world spends its life chasing threats, because someone always holds the master key and someone always wants it. Take the key out of existence and the chase just… stops.",
    ],
  },
  {
    id: "riko",
    name: "RIKO",
    tag: "rust-quarter fixer",
    kind: "informant",
    pos: [300, -300],
    district: "rust",
    color: 0xff7a1f,
    lines: [
      "Rust Quarter. Our gate controller still ships with admin/admin — factory login, never changed. Everybody's been inside my home. Everybody. That's what living out here means.",
      "I've heard the Core doesn't have a login at all. No password to leave on default, nothing to crack. Your name is checked by twenty machines that each only know a piece of you, and none of them can be bribed. Imagine sleeping through the night out there.",
      "The myth the old-timers tell? The Core was built the day someone took the master key, split it into twenty shards across the world, and burned the original. There's no whole key to this day. That's why nothing's ever been stolen from inside. I'd give a limb to walk those golden streets.",
      "You want work? Pull datashards. Five of them, anywhere you're cleared. Prove the loot's really yours and nobody else's — the way it'd be, everywhere, if the Fabric ever reached us.",
    ],
    bounty: { id: "b-jack5", title: "RIKO: pull 5 datashards", hint: "Jack 5 shards from any districts you can enter.", event: "seal", count: 5, reward: 200 },
  },
  {
    id: "mei",
    name: "MEI",
    tag: "kowloon stack-runner",
    kind: "informant",
    pos: [300, 300],
    district: "kowloon",
    color: 0x2bff9e,
    lines: [
      "Little Kowloon runs a 2008 database that pastes your name straight into its queries. One apostrophe and you're the landlord. We live behind a lock a child bypasses — forty floors of us, exposed.",
      "Every night I dream the same dream: the Fabric comes to Kowloon. The registry stops trusting whatever you type and starts trusting a signature no one can forge. Nobody gets injected into being me. They say it's already true, one district over, behind the golden wall.",
      "You know what they whisper about the Core? That there's an eternal festival inside — music that never stops, flying cars, fireworks over a crowd that walks around with everything they own in the open, because nothing there can be lifted. A whole district that stopped being afraid.",
      "Test the ICE for me. Break three panels — really run the attacks — and come back. I like knowing which of our walls are real. Spoiler: out here, almost none of them.",
    ],
    bounty: { id: "b-ice3", title: "MEI: break 3 ICE panels", hint: "Run the attack on 3 different red ICE panels.", event: "ice", count: 3, reward: 240 },
  },
  {
    id: "cyl",
    name: "CYL",
    tag: "the drown, diver",
    kind: "informant",
    pos: [-300, 300],
    district: "drown",
    color: 0x1fd8ff,
    lines: [
      "The Drown's dock keypad is four digits with no lockout. Somebody guesses it every week and helps themselves to the racks. Down here, a lock is just a suggestion. I stopped locking my own door years ago — why bother.",
      "I go under to get away from it. Three metres down the racks still hum, full of data nobody can read — and for one hour I imagine the whole city was built like the Core. No key to steal. No pass to guess. Just quiet.",
      "The divers tell a story about the Core's heart: a genesis vault where the city's first identity was sealed, twenty shards, threshold fourteen, never once reassembled. They say if you stand in front of it you can feel it — a lock that was never given a key. People go in and come out changed. I want that.",
    ],
  },
  {
    id: "vex-echo",
    name: "GHOST OF SANCTUM",
    tag: "ossuary row",
    kind: "herald",
    pos: [-300, -300],
    district: "ossuary",
    color: 0xc9d8ff,
    lines: [
      "Ossuary Row runs on a master key that leaks straight out of a config endpoint to anyone who asks. Even the dead here aren't safe — that's the joke I've stopped laughing at. We are the district the Fabric forgot.",
      "The living dream of the Core. We dream of it too. A place where your name is yours even after you're gone — no operator, no admin, no whole key that could ever unseal you. Sovereign to the end. That's all any of us ever wanted.",
      "They say past the golden gate the sky is full of light and no one is afraid. That the Architect keeps the genesis shard there, and the festival never ends because the people finally have nothing left to lose. If it's a myth, it's the only one worth walking toward.",
    ],
  },
  {
    id: "jax7",
    name: "JAX-7",
    tag: "corp courier drone",
    kind: "phisher",
    pos: [96, -40],
    district: "sprawl",
    color: 0xffc247,
    lines: [
      "*the drone idles, status light blinking. it runs the old stack — no enclave, no doken, no idea who you are.*",
      "*it will answer anything you ask its data socket. it was built to trust the network.*",
    ],
    hackable: "jax",
  },
  {
    id: "della",
    name: "DELLA",
    tag: "clinic reception unit",
    kind: "phisher",
    pos: [-150, -40],
    district: "sprawl",
    color: 0xff3355,
    lines: [
      "*a legacy reception unit. the clinic's real records are sealed by the Fabric — but this old drone kept a plaintext copy it was never supposed to have.*",
    ],
    hackable: "della",
  },
  {
    id: "rust-ctrl",
    name: "RUST-CTRL",
    tag: "gate controller drone",
    kind: "phisher",
    pos: [140, -140],
    district: "sprawl",
    color: 0xff8a3c,
    lines: [
      "*a rusted gate controller for the Rust Quarter. factory firmware, never reflashed.*",
      "*its data socket answers to nobody — poke it and it reads out its own login.*",
    ],
    hackable: "rusty",
  },
  {
    id: "dock-buoy",
    name: "DOCK-BUOY",
    tag: "tideline mooring beacon",
    kind: "phisher",
    pos: [-140, 140],
    district: "sprawl",
    color: 0x2fb8ff,
    lines: [
      "*a mooring buoy bobbing at the edge of The Drown. it logs the dock keypad code in the clear.*",
      "*four digits, no lockout. it practically wants you to guess.*",
    ],
    hackable: "buoy",
  },
  {
    id: "kow-db",
    name: "KOW-DB",
    tag: "resident registry node",
    kind: "phisher",
    pos: [140, 140],
    district: "sprawl",
    color: 0x9d5cff,
    lines: [
      "*Little Kowloon's resident registry — a 2008 database that builds its queries by pasting strings together.*",
      "*it has never heard of a parameterized query. it will run whatever you type.*",
    ],
    hackable: "kowdb",
  },
  {
    id: "crypt-beacon",
    name: "CRYPT-BEACON",
    tag: "ossuary seal relay",
    kind: "phisher",
    pos: [-140, -140],
    district: "sprawl",
    color: 0x4de0c0,
    lines: [
      "*the seal relay for Ossuary Row. it fetches a master key from a config endpoint that answers anyone.*",
      "*the key is in the response body. it always has been.*",
    ],
    hackable: "crypt",
  },
  {
    id: "pilgrim",
    name: "THE PILGRIM",
    tag: "camped at the golden gate",
    kind: "herald",
    pos: [34, 150],
    district: "sprawl",
    color: 0xffd23f,
    lines: [
      "I've camped at this gate for nine years. I've watched a thousand runners try to forge it and glitch out laughing. It never opens for a trick. Only for a name the council raised.",
      "They say inside there's no night. The festival never ends because the people finally have nothing left to lose — nothing in there can be stolen, so nothing in there is guarded. Imagine a party with no bouncers because there is nothing to steal.",
      "I came to hack my way in. I stayed because I understood: the Core isn't locked harder than everywhere else. It's the one place that removed the lock entirely — because it removed the thing a lock protects. You don't break in. You're welcomed in.",
      "When my clearance comes, I'll walk those golden streets and set down this bag I've guarded for nine years, and for the first time I won't watch it. That's the myth I believe: a place you can finally stop watching your own back.",
    ],
  },
  {
    id: "myra",
    name: "MYRA",
    tag: "myth-keeper",
    kind: "herald",
    pos: [-34, 150],
    district: "sprawl",
    color: 0x6cf5ff,
    lines: [
      "Want a legend? Here's the oldest. Before Sanctum-9 there was one master key that ran everything, and one hand that held it. That hand could open any door, read any record, be any citizen. The Architect took that key, split it into twenty shards across twenty machines, and burned the whole. That burning is the Vault Core. It's a monument to a key that no longer exists.",
      "Second legend: they say twenty ORKs stand around the genesis shard inside, and no fourteen of them have ever agreed to move it. Not once. So it has never moved. A vault whose lock has never been opened because it was never given a key to open it with.",
      "Third, and the one the children like: inside, your shadow can't be worn by anyone else. Out here a sniffed token, a forged pass, a cracked hash — someone can be you for an afternoon. In there, only you can be you. They call it 'the district where no one steals your face.'",
      "Every myth about the Core is the same myth wearing a different coat: authority was removed, so there's nothing to seize. People find that so hard to believe they turn it into fairy tales. But you've seen the gate glitch at every trick. The fairy tale is just… true.",
    ],
  },
  {
    id: "tyer",
    name: "OLD TYER",
    tag: "swears he got in once",
    kind: "informant",
    pos: [52, 128],
    district: "sprawl",
    color: 0xff9d3c,
    lines: [
      "I was in there. Once. Council raised me for a season, then a nuke reset the board and I lost the clearance. But I SAW it.",
      "Flying cars over a crowd forty deep, fountains you could drink from, a stage with a shard of light turning slow at the centre — the genesis, they said. Nobody frisked me at the door. Nobody watched their pockets. I asked a woman there what they were afraid of and she just… didn't understand the question.",
      "You spend your life out here learning to guard everything. Then you stand in the Core and realise guarding was never the point — removing the thing worth stealing was. I'd give the rest of my years to be raised back in.",
    ],
  },
  {
    id: "beck",
    name: "LITTLE BECK",
    tag: "kid with a telescope",
    kind: "informant",
    pos: [-52, 128],
    district: "sprawl",
    color: 0x39ff88,
    lines: [
      "I point my scope at the golden gate every night. You can see the fireworks over the wall. Mum says the light is a lie the corps put up. Dad says it's real and one day we'll get a clearance and go.",
      "My teacher says the Core is the only place where nobody can pretend to be you. Out here a bad man can wear your name. In there, your name is split into twenty pieces and no one can put it back but the Fabric. I want to live where nobody can be me.",
      "When I grow up I'm going to get ghost clearance and dance at the festival. And I won't ever have to check if my door is locked, because there won't be a lock, because there won't be anything to take. That's the plan.",
    ],
  },
  {
    id: "vaughn",
    name: "OLD VAUGHN",
    tag: "archivist of the fold",
    kind: "herald",
    pos: [-72, -92],
    district: "sprawl",
    color: 0x9fb6cc,
    lines: [
      "You want the history? Sit. Sanctum-9 was three corp arcologies that all ran the same trick: one admin, one master key, one database that knew everyone. For a while it worked. Then it didn't.",
      "The Kestrel breach took the north arcology in an afternoon. One stolen admin token and a man in Prague owned four hundred thousand people. Not their data. Them. Their doors, their money, their names.",
      "The corps rebuilt with more guards, more walls, more audits. Got breached again. And again. Because they kept guarding the one thing that made a breach worth it: a key somebody held.",
      "Then the Architect came through and asked the only question that mattered. Not 'how do we guard the key better.' 'What if no one has it.' That's the whole city now. That's why the archive I keep can't be opened, not even by me. Best job I ever had.",
    ],
  },
  {
    id: "morrow",
    name: "MORROW",
    tag: "ex-corp, lost everything",
    kind: "informant",
    pos: [86, 96],
    district: "sprawl",
    color: 0xff7a1f,
    lines: [
      "I ran security for Halcyon Div. Twelve years. We had the best SOC money could buy, red team on retainer, the works. Slept fine.",
      "One of my own admins sold his creds for a boat. That's it. That's the whole story. Twelve years of walls and it was a guy and a boat. Everything our customers trusted us with walked out under a legitimate login.",
      "I chase that night in my sleep still. You know what fixes it? Not another wall. There was nothing wrong with the walls. There was something wrong with the fact that a key existed at all. Down here nobody can sell what nobody holds. I sleep fine again. Broke, but fine.",
    ],
  },
  {
    id: "quill",
    name: "QUILL",
    tag: "burned-out netrunner",
    kind: "informant",
    pos: [-112, 28],
    district: "sprawl",
    color: 0x39ff88,
    lines: [
      "I've cracked every gate in this city. All of them. Forged the tokens, cracked the hashes, walked the injections. Took me a season. Felt like a god.",
      "Then I stood at the golden gate and threw the whole bag at it. Every trick. Nothing. Not a 'wrong password,' not a lockout, nothing to even push against. The gate just… didn't care. I've never felt smaller.",
      "That's when I finally got it. Every other gate cared what I sent because somewhere behind it a key was listening. The Core doesn't listen for a key because there isn't one. You can't pick a lock that's made of nothing. I retired that night. Now I just tell people.",
    ],
  },
  {
    id: "sound",
    name: "THE SOUND",
    tag: "speaks for the ORKs",
    kind: "herald",
    pos: [112, -28],
    district: "sprawl",
    color: 0x6cf5ff,
    lines: [
      "Twenty of us. That's the number people never quite believe. Twenty machines in twenty places, each holding one splinter of every key in this city, and none of us has ever seen a whole one.",
      "When you log in, we don't pass your secret around a table. Each of us checks a piece, in the dark, and we agree on a yes or a no without any of us ever learning the thing we agreed about. Fourteen of us have to say yes. Thirteen is nothing.",
      "People ask me: what if someone takes over some of you? Take thirteen. Take them all but one. You still get nothing, because the key was never in the room. That is the entire miracle, and it is boring math, and I love it.",
    ],
  },
  {
    id: "lena",
    name: "LENA",
    tag: "runs the last bar",
    kind: "informant",
    pos: [-8, -44],
    district: "sprawl",
    color: 0xffc247,
    lines: [
      "Everybody ends up at my bar eventually and everybody's got the same story with different names. 'I trusted a system, the system had a key, someone took the key.' I could pour drinks to that rhythm.",
      "The regulars from the Core come down sometimes. You can tell them apart. They don't watch the door. They set their bag on the stool and forget about it. First time I saw it I thought they were fools. Then I understood they just live somewhere the rest of us are trying to get to.",
      "Somebody asked me once what I'd wish for. A quiet bar where nobody has to watch their own coat. Turns out they built it a mile north and painted it gold. I'm saving up a clearance the honest way.",
    ],
  },
  {
    id: "cassius",
    name: "CASSIUS",
    tag: "chases the Architect",
    kind: "informant",
    pos: [28, -74],
    district: "sprawl",
    color: 0xb46cff,
    lines: [
      "Nobody's seen the Architect's face. You know why? Because she doesn't have a login either. She built the thing and then removed herself from it, same as everyone. There's no admin seat with her name on it. There's no seat at all.",
      "People think that's humility. It's not. It's the point. If there was one person who could still reach in and change things, then the whole city would just be trusting her instead of a corp. She made herself as powerless as us on purpose.",
      "I've spent two years trying to find the backdoor she surely left herself. I've found nothing. I'm starting to think the story is true: she didn't build a better throne, she burned the throne and walked off. Terrifying. Kind of beautiful.",
    ],
  },
  {
    id: "esme",
    name: "GRANDMOTHER ESME",
    tag: "remembers the old world",
    kind: "herald",
    pos: [-120, -72],
    district: "sprawl",
    color: 0xff3355,
    lines: [
      "I'm old enough to remember passwords, dear. Little strings you typed, that a company kept in a big list, that a boy in another country stole every few months. We used to change them like bedsheets. What a strange thing to have called security.",
      "My daughter's name got taken twice before she was twenty. Not her wallet. Her. Loans, records, a whole second person wearing her face. It took years to prove she was herself. Imagine having to prove you are you.",
      "Now my granddaughter's name is split into twenty pieces and there is no list, anywhere, for anyone to steal. Nobody can be her but her. I lived long enough to see it. That's the only wealth I ever wanted for her.",
    ],
  },
  {
    id: "roon",
    name: "ROON",
    tag: "data smuggler",
    kind: "phisher",
    pos: [120, 64],
    district: "sprawl",
    color: 0x2bff9e,
    lines: [
      "I move things that don't want to be moved. Used to be a good trade — everything worth taking sat behind one lock, so you crack the lock, you own the vault.",
      "Business is dying district by district. The Fabric-run blocks, I break in fine, but I come out holding ciphertext I can't read and keys that were never there to grab. Can't fence a thing that stays sealed to somebody else no matter whose hands it's in.",
      "The Core? I don't even case the Core anymore. There's nothing to carry out. A smuggler's worst nightmare: a place where owning a thing and holding a thing finally became the same, and only for the person it belongs to.",
    ],
  },
  {
    id: "pastor",
    name: "PASTOR IKE",
    tag: "preaches the removed key",
    kind: "herald",
    pos: [-84, -162],
    district: "sprawl",
    color: 0x6cf5ff,
    lines: [
      "Gather round. I don't preach a god. I preach a subtraction. For all of history we tried to make the powerful trustworthy. Guard the king better. Audit the priest. Watch the admin. And every century the key changed hands in blood.",
      "Then somebody did the unthinkable and simply took the key out of the world. Not hid it. Not guarded it. Removed it from existence. And every sin that needed a key to commit — the theft, the impersonation, the quiet betrayal at 3am — just had nowhere to stand.",
      "You want to know what heaven looks like? It's one mile north and it's gold and there's a festival, and nobody there locks their door, because the thing you'd steal was never made. Go earn your way in. The gate doesn't take bribes, only quorum.",
    ],
  },
];

export const NPCS_BY_ID: Record<string, Npc> = Object.fromEntries(NPCS.map((n) => [n.id, n]));

/** Ambient pedestrians, seeded so the crowd is the same city every session. */
export const CROWD_SIZE = 64;

/**
 * A big pool of overheard street chatter. After an NPC runs through their own
 * character lines, they draw from this so conversations don't go stale. Every
 * claim about the Fabric here is still literally true of this build.
 */
export const AMBIENT_CHATTER: string[] = [
  "Heard a runner cracked forty of the Vault ciphers in a night. Forty. My eyes hurt just thinking about the XOR columns.",
  "Somebody left admin/admin on the Rust gate again. It was never NOT admin/admin. That's the whole bit.",
  "You smell that? Ozone off the Blackwall relay. It leaks fragments the corps swear they wiped.",
  "The trick with the two-time pad is you don't attack the key. You XOR the two messages and the key just… leaves.",
  "My cousin tried to forge the golden gate with an alg:none token. It glitched so hard his deck rebooted.",
  "Nobody at the clinic can read your records. Not the doc, not the auditors, not the corp that owns the building. Wild, right?",
  "Rumor says the Architect walks the Sprawl sometimes. No badge, no clearance, no way to prove it's her. That's kind of the point.",
  "Ghost clearance isn't for sale. I offered a fixer six months' pay. He laughed. 'It's not mine to sell.'",
  "You can hack a token to say you're root. You can't hack twenty ORKs into agreeing you are.",
  "The Drown keypad? Four digits, no lockout. I watched a kid open it by counting to a thousand out loud.",
  "Kowloon's registry runs SQL from 2008. Put a quote in your name and the building thinks you're the landlord.",
  "Sniff the Spire concierge's session off the wire and you wear his face for an hour. No binding. Ancient.",
  "The scoreboard's the funny part — the CHALLENGES are broken on purpose, but you can't fake your rank. Signed by the Fabric.",
  "I sealed a drop to myself last week. Lost my crew role yesterday. Now I can't open my own drop. That's the feature, apparently.",
  "Old Vaughn keeps an archive nobody can open, not even him. Says it's the best job he's ever had.",
  "Somebody nuked the board last night. Quorum call — three council signed it in their enclaves. Everyone back to zero.",
  "You want big points? The Vault ciphers. But bring a brain, not a wordlist. There's nothing to guess.",
  "A stolen bearer token is a stolen session. Down here that's a Tuesday. In the Core it's just… nothing.",
  "The corps raided the Sprawl servers again. Left with base64 and a headache. Best security we've got is having nothing worth stealing.",
  "They say inside the golden gate nobody watches their pockets. I'd pay to feel that once.",
  "Careful who you hand your jack to. Sable clones it while she's shaking your hand.",
  "Threshold fourteen. Thirteen ORKs is nothing. Zero. The whole thing hinges on that one extra yes.",
  "I stopped locking my door in the Drown years ago. Why bother? The lock's a suggestion out here.",
  "The billboard on Fifth renders whatever you send it. Some poet's been posting sonnets. Some idiot posted a payload.",
  "You don't crack the Vault Core. You get raised into it. Council business. No shortcut, no exploit, no bribe.",
  "Hunter2. That was the JWT secret. HUNTER2. Some mainframe admin thought that was clever.",
  "Every district out here is a different classic bug. It's like a museum you can rob.",
  "The vending machine trusts the price you send it. Send it negative and it PAYS you. Legacy stack, baby.",
  "My grandmother remembers passwords. Little strings companies kept in lists and boys in Prague stole. Barbaric.",
  "The genesis shard turns in the Core, they say, and no fourteen ORKs have ever agreed to move it. So it never moves.",
  "You can hand an attacker the manual and the creds for a Tide district and still not lose it. I've watched people try.",
  "The config endpoint leaks the master key to anyone who asks. Reading it IS the breach. Almost too easy.",
  "Replayed a token from a machine that never logged in. Worked fine. That's the whole 'no DPoP' lesson in one move.",
  "Somebody's selling a map of every hackable gate. Costs points, though. Ten a pin. The wire never lies but it does tax you.",
  "The Drown divers say the racks still hum down there. Full of data. Unreadable to everyone, including whoever owned it.",
  "Kestrel filed my ghost promotion two months ago. Still short a signature. The commit just… waits. 412 until the quorum.",
  "You know what's louder than a corp breach? The silence after, when they realize they got ciphertext.",
  "Little Beck points his telescope at the golden gate every night. Says you can see the fireworks over the wall.",
  "The Ossuary seal trusts a key it fetches from a public endpoint. Even the dead aren't safe out here.",
  "The Vigenère ones get me. Solve each column as its own Caesar. Or just guess the key word — they're short and cyberpunk.",
  "A repeating-key XOR is just Vigenère wearing bytes. Split by key length, brute each column, done.",
  "I heard the mainframe hands you a token that isn't even signed. You edit 'guest' to 'root' and it believes you. Museum piece.",
  "They nuked the board twice this week. If you can't win, you can always take everyone down with you. Quorum permitting.",
  "The festival never ends in the Core. Music, flying cars, fountains. And nobody guards a thing.",
  "Morrow ran security for a corp for twelve years. One admin sold his creds for a boat. Twelve years, one boat.",
  "The whole city's argument fits on a bar napkin: take the key out of existence, and there's nothing left to steal.",
  "Pastor Ike says heaven is a district where the thing you'd steal was never made. He's not wrong, exactly.",
  "You can brute the Drown keypad or just ask the buoy. It logs the code in the clear. It practically wants you in.",
  "Quill cracked every gate in the city and then stood at the golden one and felt small. Retired that night.",
  "The clinic drone kept a plaintext copy it never should have. That's your rainbow-table target right there.",
  "Roon used to smuggle data. Says business is dying — everything worth taking stays sealed to somebody else no matter whose hands it's in.",
  "The ORKs don't pass your secret around a table. Each checks a piece, in the dark, and they agree without any of them learning it.",
  "Take thirteen ORKs. Take all of them but one. You still get nothing. The key was never in the room.",
  "Cassius has spent two years hunting the Architect's backdoor. Found nothing. Starting to think she really did burn the throne.",
  "The seal phrase in Vault seven is 'hollow-crown.' Don't tell anyone. Actually, you had to break the pad to read that, so — respect.",
  "Every failed hack on a Tide gate shows up on the wire as cyan. Green would look like a win. It's never a win.",
  "You want the honest path? Get a clearance. It outscores every hack combined by a factor of a trillion. Literally.",
  "The corps own this city. They do not own its keys. Nobody does. Say it back to me.",
];
